### ISSUE TITLE
Establecer conexion con la base de datos

### ISSUE THREAD

**Issue by RobertoRodriguezNunez** [contemporanica/api#2]
Código de ejemplo:
![Image](https://user-images.githubusercontent.com/101112990/216570819-f8a92d57-843a-4764-990c-d7f96c75ec3b.png)

**Comment by bernat13** [comment]
@RobertoRodriguezNunez, hacer una clase model, donde pongamos todo el acceso a la bbdd, así separamos las rutas del modelo de datos.

si en un futuro quisieramos cambiar el motor de bbdd por sql server, mongo o oracle, solo deberiamos reimplementar esas clases sin tocar las rutas.

por cierto, suerte que has puesto un ejemplo en codigo, por que con la imagen, es poco útil. no se puede copy and paste.
