### ISSUE TITLE
Arreglar conexion entre dos contenedores de docker compose 

### ISSUE THREAD

**Issue by Caastan** [contemporanica/api#65]
Bernat no salen los console logs ni antes de las consultas ni antes de hacer el console log del puerto a ver si tu puedes arreglarlo.

**Comment by Caastan** [comment]
Ya te he creado la rama desde dev, cuando vayas a hacer la pull request para probarla ponle latest de etiqueta al contenedor.

**Comment by bernat13** [comment]
@Caastan creo que se lo que puede ser. 

Puede ser que GitHub actions este publicando la rama main, sin los cambios que habéis hecho en dev. Esta noche lo pruebo.

Es una hipòtesi, pero explicaria porque no veiais los console logs qué poniais en el código.
